/*
 * File: app/view/FinanceViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Finance.view.FinanceViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.finance',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Date'
	],

	stores: {
		LedgerStore: {
			fields: [
				{
					name: 'ledgerId'
				},
				{
					name: 'amount'
				},
				{
					type: 'date',
					name: 'date',
					dateFormat: 'F j, Y',
					dateReadFormat: 'F j, Y'
				},
				{
					name: 'name'
				},
				{
					name: 'notes'
				}
			]
		}
	}

});