/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArchitectTemplate.view.MyPanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.mypanel',

	requires: [
		'ArchitectTemplate.view.MyPanelViewModel',
		'Ext.button.Button',
		'Ext.container.Container'
	],

	viewModel: {
		type: 'mypanel'
	},
	frame: true,
	minHeight: 500,
	minWidth: 500,
	title: 'Architect Template',
	defaultListenerScope: true,

	items: [
		{
			xtype: 'button',
			text: 'Do Ajax Request',
			listeners: {
				click: 'onButtonClick'
			}
		},
		{
			xtype: 'container',
			height: 500,
			html: 'Full Screen App With<br />Min Width & Height Example 500x500<br /><br />Min Width/Height is set on<br />"My Panel"<br /><br />You can delete this container after reading this.',
			padding: '90px 0 0 10px',
			style: 'background-color:green; font-size:30px; color:white; text-align:center;',
			width: 500
		}
	],

	onButtonClick: function(button, e, eOpts) {
		this.doAjaxRequest();
	},

	doAjaxRequest: function() {
		//let job = this.queryById('job').getValue();

		//let grid = this.queryById('jobGrid');

		//this.clearJobGrid();

		AERP.Ajax.request({
			url:'/controllerName/methodName',
			jsonData: {
				job:job
			},
			success:function(reply){
				//this.loadedJob = job;

				//store.loadData(reply.data);
			},
			scope:this,
			//mask:grid
		});
	}

});