/*
 * File: app/view/ScheduleViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Schedule.view.ScheduleViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.schedule',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Date'
	],

	stores: {
		EmployeeStore: {
			fields: [
				{
					name: 'employeeId'
				},
				{
					name: 'name'
				}
			]
		},
		EmployeeScheduleStore: {
			fields: [
				{
					name: 'employeeId'
				},
				{
					name: 'employeeNumber'
				},
				{
					name: 'firstName'
				},
				{
					name: 'lastName'
				},
				{
					type: 'date',
					name: 'currentClockIn',
					dateFormat: 'h:ia',
					dateReadFormat: 'h:ia'
				},
				{
					name: 'position'
				}
			]
		},
		LaborHistoryStore: {
			fields: [
				{
					name: 'laborId'
				},
				{
					type: 'date',
					name: 'startTime',
					dateFormat: 'F j, Y g:i a',
					dateReadFormat: 'F j, Y g:i a'
				},
				{
					type: 'date',
					name: 'endTime',
					dateFormat: 'F j, Y g:i a',
					dateReadFormat: 'F j, Y g:i a'
				},
				{
					name: 'hoursWorked'
				}
			]
		}
	}

});