/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PasswordReset.view.MyViewport', {
	extend: 'Ext.container.Viewport',
	alias: 'widget.myviewport',

	requires: [
		'PasswordReset.view.MyViewportViewModel',
		'Ext.toolbar.Toolbar'
	],

	viewModel: {
		type: 'myviewport'
	},
	defaultListenerScope: true,

	layout: {
		type: 'vbox',
		align: 'stretch'
	},
	items: [
		{
			xtype: 'usertoolbar'
		}
	],
	listeners: {
		afterrender: 'onViewportAfterRender',
		resize: 'onViewportResize'
	},

	onViewportAfterRender: function(component, eOpts) {
		var form = Ext.create('widget.passwordreset');

		this.passwordReset = Ext.create('Ext.window.Window', {
			header: false,
			layout: 'fit',
			closable:false,
			resizable:false,
			bodyPadding:5,
			items:[form]
		});
		this.passwordReset.show();
	},

	onViewportResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
		this.passwordReset.center();
	}

});