/*
 * File: app/view/Job.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Job.view.Job', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.job',

	mixins: [
		'DocForm'
	],
	requires: [
		'Job.view.JobViewModel',
		'Job.view.JobRoutings',
		'Job.view.JobBom',
		'Ext.toolbar.Toolbar',
		'Ext.form.field.ComboBox',
		'Ext.form.field.Date',
		'Ext.tab.Panel',
		'Ext.tab.Tab'
	],

	viewModel: {
		type: 'job'
	},
	frame: true,
	minHeight: 500,
	minWidth: 500,
	title: 'Job',
	defaultListenerScope: true,

	layout: {
		type: 'vbox',
		align: 'stretch'
	},
	dockedItems: [
		{
			xtype: 'toolbar',
			flex: 1,
			dock: 'top',
			itemId: 'jobToolbar',
			defaultButtonUI: 'default',
			items: [
				{
					xtype: 'button',
					margin: '0 0 0 5',
					icon: '/inc/img/silk_icons/arrow_up.png',
					text: 'View Parent Job',
					listeners: {
						click: 'onButtonClick'
					}
				},
				{
					xtype: 'container',
					margin: '0 0 0 5',
					items: [
						{
							xtype: 'button',
							itemId: 'first',
							margin: '0 5 0 0',
							icon: '/inc/img/silk_icons/resultset_first.png',
							listeners: {
								click: 'onFirstClick'
							}
						},
						{
							xtype: 'button',
							itemId: 'previous',
							margin: '0 5 0 0',
							icon: '/inc/img/silk_icons/resultset_previous.png',
							listeners: {
								click: 'onFirstClick1'
							}
						},
						{
							xtype: 'button',
							itemId: 'next',
							margin: '0 5 0 0',
							icon: '/inc/img/silk_icons/resultset_next.png',
							listeners: {
								click: 'onFirstClick11'
							}
						},
						{
							xtype: 'button',
							itemId: 'last',
							margin: '0 5 0 0',
							icon: '/inc/img/silk_icons/resultset_last.png',
							listeners: {
								click: 'onFirstClick111'
							}
						}
					]
				}
			]
		}
	],
	items: [
		{
			xtype: 'container',
			padding: 10,
			layout: {
				type: 'vbox',
				align: 'stretch'
			},
			items: [
				{
					xtype: 'container',
					layout: 'hbox',
					items: [
						{
							xtype: 'textfield',
							itemId: 'jobNumber',
							fieldLabel: 'Job',
							labelAlign: 'right'
						},
						{
							xtype: 'combobox',
							itemId: 'status',
							margin: '0 0 0 15',
							fieldLabel: 'Status',
							labelAlign: 'right',
							labelWidth: 70,
							displayField: 'status',
							forceSelection: true,
							queryMode: 'local',
							valueField: 'status',
							bind: {
								store: '{StatusStore}'
							},
							listeners: {
								afterrender: 'onStatusAfterRender'
							}
						},
						{
							xtype: 'datefield',
							itemId: 'jobCreateDate',
							margin: '0 0 0 10',
							fieldLabel: 'Create Date',
							labelAlign: 'right',
							labelWidth: 70
						}
					]
				},
				{
					xtype: 'container',
					margin: '5 0 0 0',
					layout: 'hbox',
					items: [
						{
							xtype: 'combobox',
							itemId: 'part',
							width: 337,
							fieldLabel: 'Part',
							labelAlign: 'right',
							emptyText: 'BEGIN TYPING',
							hideTrigger: true,
							displayField: 'partName',
							forceSelection: true,
							minChars: 1,
							queryParam: 'partName',
							typeAhead: true,
							typeAheadDelay: 150,
							valueField: 'partId',
							bind: {
								store: '{PartStore}'
							}
						},
						{
							xtype: 'textfield',
							itemId: 'quantity',
							width: 205,
							fieldLabel: 'Quantity',
							labelAlign: 'right'
						},
						{
							xtype: 'datefield',
							itemId: 'jobStartDate',
							fieldLabel: 'Start Date',
							labelAlign: 'right',
							submitFormat: 'Y-m-d',
							listeners: {
								afterrender: 'onJobStartDateAfterRender'
							}
						}
					]
				}
			]
		},
		{
			xtype: 'tabpanel',
			flex: 1,
			itemId: 'jobTabPanel',
			bodyStyle: 'background:none',
			activeTab: 0,
			deferredRender: false,
			items: [
				{
					xtype: 'jobroutings',
					itemId: 'jobRoutingTab'
				},
				{
					xtype: 'jobbom',
					itemId: 'jobBomTab'
				}
			]
		}
	],
	listeners: {
		afterrender: 'onPanelAfterRender',
		docFormStateChanged: 'onPanelDocFormStateChangeD'
	},

	onButtonClick: function(button, e, eOpts) {
		if(!this.jobId) {
			Ext.Msg.alert('Error', "Please Load a Job First!");
			return;
		}

		AERP.Ajax.request({
			url:'/Job/readParentJob',
			jsonData:{jobId:this.jobId},
			success:function(reply) {
				this.readJob(reply.data);
			},
			scope:this,
			mask:this
		});
	},

	onFirstClick: function(button, e, eOpts) {
		AERP.Ajax.request({
			url:'/Job/readFirstJob',
			success:function(reply) {
				this.readJob(reply.data);
			},
			scope:this,
			mask:this
		});
	},

	onFirstClick1: function(button, e, eOpts) {
		if(!this.jobId) {
			Ext.Msg.alert('Error', "Please Load a Job First!");
			return;
		}

		AERP.Ajax.request({
			url:'/Job/readPreviousJob',
			jsonData:{jobId:this.jobId},
			success:function(reply) {
				this.readJob(reply.data);
			},
			scope:this,
			mask:this
		});
	},

	onFirstClick11: function(button, e, eOpts) {
		if(!this.jobId) {
			Ext.Msg.alert('Error', "Please Load a Job First!");
			return;
		}

		AERP.Ajax.request({
			url:'/Job/readNextJob',
			jsonData:{jobId:this.jobId},
			success:function(reply) {
				this.readJob(reply.data);
			},
			scope:this,
			mask:this
		});
	},

	onFirstClick111: function(button, e, eOpts) {
		AERP.Ajax.request({
			url:'/Job/readLastJob',
			success:function(reply) {
				this.readJob(reply.data);
			},
			scope:this,
			mask:this
		});
	},

	onStatusAfterRender: function(component, eOpts) {
		AppWindowManager.appOn('dropDownSelectionEditor', {
			scope:this,
			selectionchanged:function() {
				this.readJobStatuses();
			}
		});

		component.el.on({
		    contextmenu: function(event) {
		        event.stopEvent();
		        AppWindowManager.appLink('dropDownSelectionEditor', {dataKey:'jobStatus'});
		    },
		    scope:this
		});

	},

	onJobStartDateAfterRender: function(component, eOpts) {
		component.getEl().on('dblclick', function() {
		    component.setValue(new Date());
		});
	},

	onPanelAfterRender: function(component, eOpts) {
		this.docFormInit({
			toolbarId:'jobToolbar',
			addFn:'createJob',
			saveFn:'updateJob',
			deleteFn:'deleteJob',
			searchFn:'searchJobs',
			searchableFields:['jobNumber', 'part']
		});
		this.fireEvent('appdataloaded');
		this.readJobStatuses();
		this.addAppWindowManagerListeners();
	},

	onPanelDocFormStateChangeD: function(oldState, newState) {
		let fields = ['jobCreateDate'];

		if(newState !== "search") {
			fields.push('jobNumber');
		}

		for(let i in fields) {
			let field = this.queryById(fields[i]);

			field.addCls('docFormReadOnly');
			field.setReadOnly(true);
		}
	},

	addAppWindowManagerListeners: function() {
		AppWindowManager.on('applinkjob',function(linkEvent){
		    this.readJob(linkEvent.dataKey);
		    return false;
		}, this);
	},

	searchJobs: function() {
		if(!this.jobSearchWindow) {
			this.jobSearchWindow = Ext.create("Job.view.JobSearch", {
				listeners:{
					scope:this,
					jobselected:function(jobId) {
						this.readJob(jobId);
					}
				}
			});
		}

		this.jobSearchWindow.show(null, function(){
			this.jobSearchWindow.searchJobs(this.queryById('jobNumber').getValue(), this.queryById('part').getValue());
		}, this);
	},

	readJob: function(jobId) {
		AERP.Ajax.request({
			url:'/Job/readJob',
			jsonData:{jobId:jobId},
			success:function(reply) {
				this.getViewModel().getStore('PartStore').loadData([[reply.data.part, reply.data.partName]]);
				this.docFormLoadFormData(reply);
				this.jobId = jobId;
				this.queryById('jobBomTab').readJobBom(jobId);
				this.queryById('jobRoutingTab').readJobRoutings(jobId);
			},
			scope:this,
			mask:this
		});
	},

	createJob: function() {
		AERP.Ajax.request({
			url:'/Job/createJob',
			jsonData:this.docFormGetAllFieldValues(),
			success:function(reply) {
				this.readJob(reply.data);
			},
			scope:this,
			mask:this
		});
	},

	updateJob: function() {
		let jsonData = this.docFormGetAllFieldValues();
		jsonData.jobId = this.jobId;

		AERP.Ajax.request({
			url:'/Job/updateJob',
			jsonData:jsonData,
			success:function(reply) {
				this.readJob(this.jobId);
			},
			scope:this,
			mask:this
		});
	},

	deleteJob: function() {
		AERP.Ajax.request({
			url:'/Job/deleteJob',
			jsonData:{jobId:this.jobId},
			success:function(reply) {
				this.docFormReset();
				this.queryById('jobBomTab').queryById('jobBomGrid').setRootNode({});
				this.queryById('jobRoutingTab').getViewModel().getStore('JobRoutingStore').removeAll();
			},
			scope:this,
			mask:this
		});
	},

	readJobStatuses: function() {
		AERP.Ajax.request({
			url:'/DropDownSelectionEditor/readSelectionsForCombo',
			jsonData:{selectionKey:'jobStatus'},
			success:function(reply) {
				this.getViewModel().getStore('StatusStore').loadData(reply.data);
			},
			scope:this,
			mask:this
		});
	}

});