/*
 * File: app/view/JobRoutings.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Job.view.JobRoutings', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.jobroutings',

	requires: [
		'Job.view.JobRoutingsViewModel',
		'Ext.grid.Panel',
		'Ext.grid.column.Date',
		'Ext.view.Table'
	],

	viewModel: {
		type: 'jobroutings'
	},
	title: 'Job Routings',

	layout: {
		type: 'vbox',
		align: 'stretch'
	},
	items: [
		{
			xtype: 'gridpanel',
			flex: 1,
			itemId: 'jobRoutingGrid',
			bind: {
				store: '{JobRoutingStore}'
			},
			columns: [
				{
					xtype: 'gridcolumn',
					dataIndex: 'operation',
					text: 'Operation'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'workcenterName',
					text: 'Work Center'
				},
				{
					xtype: 'datecolumn',
					dataIndex: 'jobRoutingStartDate',
					text: 'Start Date'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'quantityComplete',
					text: 'Complete'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'totalQuantity',
					text: 'Total'
				}
			]
		}
	],

	readJobRoutings: function(jobId) {
		AERP.Ajax.request({
			url:'/Job/readJobRoutings',
			jsonData:{jobId:jobId},
			success:function(reply) {
				this.jobId = jobId;
				this.getViewModel().getStore("JobRoutingStore").loadData(reply.data);
			},
			scope:this,
			mask:this
		});
	}

});