/*
 * File: app/view/JobSearch.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Job.view.JobSearch', {
	extend: 'Ext.window.Window',
	alias: 'widget.jobsearch',

	requires: [
		'Job.view.JobSearchViewModel',
		'Ext.grid.Panel',
		'Ext.toolbar.Toolbar',
		'Ext.grid.column.Date',
		'Ext.view.Table'
	],

	viewModel: {
		type: 'jobsearch'
	},
	height: 500,
	width: 500,
	closeAction: 'hide',
	title: 'Job Search',
	defaultListenerScope: true,

	layout: {
		type: 'vbox',
		align: 'stretch'
	},
	items: [
		{
			xtype: 'gridpanel',
			flex: 1,
			itemId: 'jobSearchGrid',
			bind: {
				store: '{JobSearchStore}'
			},
			dockedItems: [
				{
					xtype: 'toolbar',
					dock: 'top',
					itemId: 'jobSearchToolbar'
				}
			],
			columns: [
				{
					xtype: 'gridcolumn',
					dataIndex: 'jobNumber',
					text: 'Job Number'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'part',
					text: 'Part'
				},
				{
					xtype: 'datecolumn',
					dataIndex: 'jobStartDate',
					text: 'Start Date'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'quantity',
					text: 'Quantity'
				}
			]
		}
	],
	listeners: {
		afterrender: 'onPanelAfterRender'
	},

	onPanelAfterRender: function(component, eOpts) {
		Ext.create("NiceGridMenu", {
			menuItems:[{text:'Select Job', action:'selectJob', icon:'/inc/img/silk_icons/accept.png', disabled:true}],
			callbackHandler:function(action, data) {
				switch(action) {
					case 'selectJob':
						this.fireEvent('jobselected', data.jobId);
						this.close();
						break;
				}
			},
			filterField:true,
			doubleClick:'selectJob',
			grid:this.queryById('jobSearchGrid'),
			toolbar:this.queryById('jobSearchToolbar'),
			scope:this
		});
	},

	searchJobs: function(jobNumber, part) {
		AERP.Ajax.request({
			url:'/Job/searchJobs',
			jsonData:{jobNumber:jobNumber, part:part},
			success:function(reply) {
				if(reply.data.length === 0) {
					Ext.Msg.alert("Warning", "No Results Found");
					this.close();
				} else if(reply.data.length === 1) {
					this.fireEvent('jobselected', reply.data[0][0]);
					this.close();
				}

				this.getViewModel().getStore('JobSearchStore').loadData(reply.data);
			},
			scope:this,
			mask:this
		});
	}

});