/*
 * File: app/view/EggsViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incubator.view.EggsViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.eggs',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Date'
	],

	stores: {
		EggStore: {
			fields: [
				{
					name: 'eggId'
				},
				{
					name: 'serial'
				},
				{
					type: 'date',
					name: 'layDate',
					dateReadFormat: 'Y-m-d'
				}
			]
		}
	}

});