/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Logout.view.MyViewport', {
	extend: 'Ext.container.Viewport',
	alias: 'widget.myviewport',

	requires: [
		'Logout.view.MyViewportViewModel'
	],

	viewModel: {
		type: 'myviewport'
	},
	defaultListenerScope: true,

	listeners: {
		afterrender: 'onViewportAfterRender',
		resize: 'onViewportResize'
	},

	onViewportAfterRender: function(component, eOpts) {
		var panel = Ext.create('widget.logoutpanel');

		this.logoutWin = Ext.create('Ext.window.Window', {
			header: false,
			layout: 'fit',
			closable:false,
			resizable:false,
			bodyPadding:5,
			items:[panel]
		});
		this.logoutWin.show();
	},

	onViewportResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
		this.logoutWin.center();
	}

});