/*
 * File: app/view/DrillDownViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AgileInventory.view.DrillDownViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.drilldown',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Field'
	],

	stores: {
		LocationStore: {
			fields: [
				{
					name: 'locationId'
				},
				{
					name: 'locationName'
				},
				{
					name: 'locationDescription'
				},
				{
					name: 'facilityName'
				}
			]
		},
		BinStore: {
			fields: [
				{
					name: 'binId'
				},
				{
					name: 'binName'
				},
				{
					name: 'binDescription'
				}
			]
		},
		OnHandStore: {
			fields: [
				{
					name: 'onHandId'
				},
				{
					name: 'bin'
				},
				{
					name: 'productId'
				},
				{
					name: 'productName'
				},
				{
					name: 'productDescription'
				},
				{
					name: 'quantity'
				}
			]
		}
	}

});