/*
 * File: app/view/FacilitiesViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AgileInventory.view.FacilitiesViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.facilities',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Field'
	],

	stores: {
		FacilityStore: {
			fields: [
				{
					name: 'facilityId'
				},
				{
					name: 'facilityName'
				},
				{
					name: 'facilityDescription'
				},
				{
					name: 'address'
				}
			]
		}
	}

});