/*
 * File: app/view/PurchaseOrders.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AgileInventory.view.PurchaseOrders', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.purchaseorders',

	requires: [
		'AgileInventory.view.PurchaseOrdersViewModel',
		'Ext.grid.Panel',
		'Ext.grid.column.Date',
		'Ext.view.Table'
	],

	viewModel: {
		type: 'purchaseorders'
	},
	bodyStyle: 'background:none',
	title: 'Purchase Orders',

	layout: {
		type: 'vbox',
		align: 'stretch'
	},
	items: [
		{
			xtype: 'gridpanel',
			flex: 1,
			bind: {
				store: '{PurchaseOrderStore}'
			},
			columns: [
				{
					xtype: 'gridcolumn',
					dataIndex: 'purchaseOrderNumber',
					text: 'PO #'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'product',
					text: 'Product'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'vendor',
					text: 'Vendor'
				},
				{
					xtype: 'datecolumn',
					dataIndex: 'orderDate',
					text: 'Order Date'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'quantity',
					text: 'Quantity'
				},
				{
					xtype: 'gridcolumn',
					dataIndex: 'status',
					text: 'Status'
				}
			],
			viewConfig: {
				enableTextSelection: true
			}
		}
	]

});