/*
 * File: app/view/EmployeeFormViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Employee.view.EmployeeFormViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.employeeform',

	requires: [
		'Ext.data.Store',
		'Ext.data.field.Field'
	],

	stores: {
		PositionStore: {
			fields: [
				{
					name: 'position'
				}
			]
		},
		PermissionStore: {
			fields: [
				{
					name: 'groupId'
				},
				{
					name: 'groupName'
				}
			]
		}
	}

});