/*
 * File: app/view/AgileInventory.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AgileInventory.view.AgileInventory', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.agileinventory',

	requires: [
		'AgileInventory.view.AgileInventoryViewModel',
		'AgileInventory.view.Products',
		'AgileInventory.view.DrillDown',
		'AgileInventory.view.Locations',
		'AgileInventory.view.Bins',
		'Ext.tab.Panel',
		'Ext.tab.Tab'
	],

	viewModel: {
		type: 'agileinventory'
	},
	frame: true,
	minHeight: 500,
	minWidth: 500,
	title: 'Agile Inventory',

	layout: {
		type: 'vbox',
		align: 'stretch'
	},
	items: [
		{
			xtype: 'tabpanel',
			flex: 1,
			bodyStyle: 'background:none',
			items: [
				{
					xtype: 'products'
				},
				{
					xtype: 'drilldown'
				},
				{
					xtype: 'locations'
				},
				{
					xtype: 'bins'
				}
			]
		}
	]

});