/*
 * File: app/view/EmailsViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Log.view.EmailsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.emails',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array',
        'Ext.util.Sorter'
    ],

    stores: {
        EmailStore: {
            pageSize: 30,
            remoteFilter: true,
            remoteSort: true,
            fields: [
                {
                    name: 'sendDate'
                },
                {
                    name: 'subject'
                },
                {
                    name: 'from'
                },
                {
                    name: 'to'
                },
                {
                    name: 'CC'
                },
                {
                    name: 'BCC'
                },
                {
                    name: 'mailServer'
                },
                {
                    name: 'srcIp'
                },
                {
                    name: 'srcHostname'
                },
                {
                    name: 'srcHelo'
                },
                {
                    name: 'size'
                },
                {
                    name: 'contentHash'
                }
            ],
            proxy: {
                type: 'ajax',
                noCache: false,
                simpleSortMode: true,
                url: 'readEmails',
                actionMethods: {
                    create: 'POST',
                    read: 'POST',
                    update: 'POST',
                    destroy: 'POST'
                },
                reader: {
                    type: 'array',
                    rootProperty: 'data',
                    totalProperty: 'totalRows'
                }
            },
            sorters: {
                direction: 'DESC',
                property: 'sendDate'
            }
        }
    }

});