/*
 * File: app/view/TextDetailWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Log.view.TextDetailWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.Textdetailwindow',

    requires: [
        'Log.view.TextDetailWindowViewModel',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'textdetailwindow'
    },
    height: 250,
    width: 400,
    layout: 'fit',
    closeAction: 'hide',
    title: 'Details',

    items: [
        {
            xtype: 'textareafield',
            itemId: 'text'
        }
    ],

    setText: function(text) {
        this.queryById('text').setValue(text);
        this.show();

        this.setSize('60%','60%');
        this.center();
    }

});